# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-15 12:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import employee_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number length must be between 6 and 20 numbers', regex='^\\d{6,20}$')], verbose_name='Mobile Number')),
                ('hire_date', models.DateField()),
                ('employee_type', models.CharField(choices=[('P', 'Permenant'), ('T', 'Temporary')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Allowed file types: pdf, jpg, jpeg, png'), employee_system.models.account_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
